services:
  express-app:
    container_name: expess-app-container
    build: 
      context: ~/express-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower-container



